use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

target 'AHFMMainManager_Example' do
  pod 'AHFMMainManager', :path => '../'

  target 'AHFMMainManager_Tests' do
    inherit! :search_paths

    
  end
end
